[workspace]
resolver = "2"
members = ["bench", "entrace_convert", "entrace_core", "entrace_query", "entrace_script","example", "example_generator", "gui" ]

[profile.profiling]
inherits = 'release'
debug = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
