name: "Build with nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix build -v -L .#entrace
    - run: nix build -v -L .#entrace_core
    - run: nix build -v -L .#entrace_core_lite
