name: "Build with nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build -v -L .#entrace
    - run: nix build -v -L .#entrace_core
    - run: nix build -v -L .#entrace_core_lite
    - run: nix build -v -L .#entrace_script
