name: "Build with nix"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build -v -L .#entrace
    - run: nix build -v -L .#entrace_core
    - run: nix build -v -L .#entrace_core_lite
